name = "Skyrail"
author = "RoseVulpix+fiaKaiera"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b380f3cb1298433077fe7e6719e502f55c7197c65eac2283dec198b1e44a5b6"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"
